- name: aws_s3_agent
  description: Handles AWS S3 operations
  tools:
  - list_buckets
  - list_objects
  - read_object
  - get_object_metadata
  - generate_presigned_url
  - upload_object
  - download_object
  - download_object_by_url